### ISSUE TITLE
[Bug]: White controlnet image after reopen controlnet

### ISSUE THREAD

**Issue by MarkGree** [Mikubill/sd-webui-controlnet#889] opened 2023-04-18 09:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When you hide controlnet settings and reopen it, the image turns white and becomes non-interactable.
(the same thing happens in img2img tab, but with a bit different error logs I believe)
If I try to generate image with those blank images I get this error (but the model and preprocessor still working):

```
Traceback (most recent call last):█████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.98it/s]
  File "C:\Users\user\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\user\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 363, in svgPreprocess
    if (inputs['image'].startswith("data:image/svg+xml;base64,") and svgsupport):
AttributeError: 'dict' object has no attribute 'startswith'
Loading model from cache: t2iadapter_openpose_sd14v1 [4286314e]
```

[https://pasteboard.co/h6HHPyMGz5Vz.png](Step 1-2)
[https://pasteboard.co/MaUOyVvpihxm.png](Step 4)

When I change preprocessor and model to something else, generator still uses previous preprocessor & model
(Generate one image before reopen controlnet with openpose -> change to canny -> image generation still uses openpose)

### Steps to reproduce the problem

1. Open controlnet in txt2img tab
2. Set controlnet image
3. Generate one image
4. Close controlnet settings
5. Open controlnet settings

### What should have happened?

1. The image set earlier must be in the preview
2. Switching models and preporcessor must working

### Commit where the problem happens

webui: 22bcc7be
controlnet: 0b7c3e98

### Command Line Arguments

```Shell
--medvram --xformers --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80
```

### Console logs

```Shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 25.0s (import torch: 3.9s, import gradio: 2.6s, import ldm: 1.2s, other imports: 2.0s, setup codeformer: 0.3s, load scripts: 6.1s, load SD checkpoint: 5.5s, create ui: 3.2s, gradio launch: 0.2s).
Loading model: t2iadapter_openpose_sd14v1 [4286314e]
Loaded state_dict from [C:\Users\user\stable-diffusion-webui\models\ControlNet\t2iadapter_openpose_sd14v1.safetensors]
Loading config: C:\Users\user\stable-diffusion-webui\models\ControlNet\t2iadapter_openpose_sd14v1.yaml
ControlNet model t2iadapter_openpose_sd14v1 [4286314e] loaded.
Loading preprocessor: openpose
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.64it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.81it/s]
Traceback (most recent call last):█████████████████████████████████████████████████████| 20/20 [00:07<00:00,  3.91it/s]
  File "C:\Users\user\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\user\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 363, in svgPreprocess
    if (inputs['image'].startswith("data:image/svg+xml;base64,") and svgsupport):
AttributeError: 'dict' object has no attribute 'startswith'
Loading model from cache: t2iadapter_openpose_sd14v1 [4286314e]
Loading preprocessor: openpose
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.37it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.07it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  4.07it/s]
```

**Comment by MarkGree** [comment] 2023-04-18 09:36
You can reload the page and it will be working again. But it clears all the settings you set in the UI

**Comment by ljleb** [comment] 2023-04-18 09:46
Yes, this is a known issue. Duplicate of #677

**Closed** 2023-05-05 19:19 UTC
