### ISSUE TITLE
Trojan detected (is it?)

### ISSUE THREAD

**Issue by gitihobo** [Mikubill/sd-webui-controlnet#1653] opened 2023-06-18 04:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\oneformer\250_16_swin_l_oneformer_ade20k_160k.pth 

### Steps to reproduce the problem

Antivirus

### What should have happened?

Behavior is normal 

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

no

### Console logs

```Shell
no
```

**Comment by huchenlei** [comment] 2023-06-19 15:21
Closing as lack further context. Cannot reproduce with the steps provided.

**Closed by huchenlei** 2023-06-19 15:21 UTC
