### ISSUE TITLE
Bug: Calling api conflicts with 'additional-networks'

### ISSUE THREAD

**Issue by KotoriKoi** [Mikubill/sd-webui-controlnet#294] opened 2023-02-22 15:08 UTC
![image](https://user-images.githubusercontent.com/91445888/220660602-ba155cb4-ec6a-43fd-aa13-1afdb026cbf7.png)

Steps to reproduce: download the new version of Controlnet and Additional-networks, use the test_api.py call, and the webui console pops up an error.
I don't know if it's an api problem or what, because Controlnet and Additional-networks are similar in many places, it may be a conflict of ontology. Turning off Additional-networks in the extension does not solve it, the Additional-networks folder must be completely deleted. After the deletion, the api can be called and the image is generated normally, but the relevant api of Controlnet disappears in http://127.0.0.1:7860/docs#/.

**Comment by Mikubill** [comment] 2023-02-22 15:11
Confirmed. cc @sangww

**Comment by yxgwar** [comment] 2023-02-23 04:38
I also met the same problem. Here are the reasons I understand.
When webui start, all the extensions will be registered to `ScriptRunner.alwayson_scripts`(in stable-diffusion-webui/modules/scripts.py, line 252), the order is Additional-networks, Controlnet. When you use the api, your args will be located in `p.scripts_args`, and will be divided into different parts which will be send to different extensions.

    def process_batch(self, p, **kwargs):
        for script in self.alwayson_scripts:
            try:
                script_args = p.script_args[script.args_from:script.args_to]
                script.process_batch(p, *script_args, **kwargs)
            except Exception:
                print(f"Error running process_batch: {script.filename}", file=sys.stderr)
                print(traceback.format_exc(), file=sys.stderr)

So the earlier extension registers, the earlier it will get the args from `p.script_args`. Then Addition-networks takes the first few parameters that are prepared for Controlnet, so Addition-networks reports errors. Then Controlnet gets the leftover parameters, finds they are not enough, also reports errors. But I can't understand the reason why Controlnet reports error before Addition-networks.(My english is not good.I hope you can understand.)

**Comment by Mikubill** [comment] 2023-02-24 17:03
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/3691d1130b03823cb3e9fe778a533a5ffb633aac.

**Closed as completed** 2023-02-25 20:46 UTC
Labels: bug
