### ISSUE TITLE
[Bug]: reference_only is crashing

### ISSUE THREAD

**Issue by FrancisBourre** [Mikubill/sd-webui-controlnet#1287] opened 2023-05-15 09:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I cannot use reference_only.
Tried many combinations, crashed every time.

### Steps to reproduce the problem

1. Enable controlnet on txt2img tab
2. Drop an image
3. Select reference_only in the combo box
4. Click on generate

### What should have happened?

Reference Only should not throw an exception and crash the web ui.

### Commit where the problem happens

webui:
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
controlnet: 
Version 1.1.173
d831043cb81e97724ccf9f071da391d479440a77

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--skip-torch-cuda-test --no-half
```

### Console logs

```Shell
Loading preprocessor: reference_only
preprocessor resolution = 512
  0%|                                                                                                                                                         | 0/20 [00:00<?, ?it/s]ControlNet used torch.float32 VAE to encode torch.Size([2, 4, 64, 64]).
/AppleInternal/Library/BuildRoots/9941690d-bcf7-11ed-a645-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:706: failed assertion `[MPSTemporaryNDArray initWithDevice:descriptor:] Error: NDArray dimension length > INT_MAX'
zsh: abort      ./webui.sh
```

### Additional information

I'm using a mac M2 with 96GB ram.

**Comment by gregorio500** [comment] 2023-05-15 21:16
same here. I've already updated, but it doesn't help with my Mac M1. When I try to use 'reference only' in ControlNet, it throws the error: "Python quit unexpectedly." I've tried using several models, but the same error occur.
More details about this error:

```
Error: NDArray dimension length > INT_MAX'
zsh: abort      ./webui.sh --no-half --disable-safe-unpickle
(base) gregorio@greg-MacBook-Pro stable-diffusion-webui % /opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
```

**Comment by mynameisbill** [comment] 2023-05-15 21:52
Same story here. Running on M1 Ultra with 128 GB Ram. Python quits every time I run reference_only or reference_adain+attn. Curiously, reference_adain works just fine.

**Comment by rainx** [comment] 2023-05-16 13:19
the same issue, I am using Apple M1 Pro with 32RAM.  Python 3.10.10

**Comment by rootlake** [comment] 2023-05-16 14:45
Confirmed here as well on an M1 Pro. Reference_adain works, the other reference models do not.

**Comment by mynameisbill** [comment] 2023-05-16 17:08
as @shawnington pointed out, it does work when "Upcast cross attention layer to float32" is switched off in Stable Diffusion settings. I did that, used it for awhile, and then toggled the setting back on. And now it seems to work fine. No idea why.

**Comment by gregorio500** [comment] 2023-05-17 15:45
The solution to switch off "Upcast cross attention layer to float32"  does not work for me.

**Comment by firestar222** [comment] 2023-05-19 09:45
Same for me, and "Upcast cross attention layer to float32" does not work for me either...

**Comment by Zaiwa-linus** [comment] 2023-06-07 08:23
This issue might potentially be due to certain parts of the numpy library used in reference_only not being installable without administrator privileges, although this is not definitively confirmed.

I've been able to resolve the issue using this method and have verified its operation on an M1 Pro environment with 32GB memory.

The problem should be resolved by using administrator privileges to install numpy in a virtual environment, as shown in the commands below:

```
. venv/bin/activate
pip install --upgrade pip
pip install torch torchvision torchaudio numpy --upgrade --ignore-installed
sudo pip install numpy --upgrade --ignore-installed
./webui.sh
```

I hope this post can be of help to you.

**Closed** 2023-11-21 20:19 UTC
