### ISSUE TITLE
[Bug]: ValueError: controlnet is enabled but no input image is given

### ISSUE THREAD

**Issue by loboere** [Mikubill/sd-webui-controlnet#677] opened 2023-03-29 20:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

controlnet does not load the image to process

### Steps to reproduce the problem

1-open the controlnet panel in txt2img or img2img
2-enable some controlnet
3-upload an image
4-close the control panel
5-open the control panel again

it is not seen and image cannot be loaded in the panel!

### What should have happened?

load image controlnet

### Commit where the problem happens

webui: last
controlnet: last

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
run the "Test The Trained Model" cell of colab  fast-dreambooth
```

### Console logs

```Shell
2023-03-29 20:26:35.050385: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-29 20:26:37.616177: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-29 20:26:37.616379: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-29 20:26:37.616410: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Loading weights [debf518cef] from /content/gdrive/MyDrive/Fast-Dreambooth/Sessions/acuarelin/acuarelin.ckpt
Creating model from config: /content/gdrive/.shortcut-targets-by-id/1-N00rILD1DFYx_xpfZmRc-FhO22x7pXE/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 21.0s (load weights from disk: 15.7s, create model: 1.0s, apply weights to model: 2.6s, apply half(): 1.0s, move model to device: 0.6s).
Running on public URL: https://1f49490deee6dc8298.gradio.live
✔ Connected
Startup time: 45.1s (import torch: 9.3s, import gradio: 1.4s, import ldm: 0.4s, other imports: 5.3s, setup codeformer: 0.2s, load scripts: 3.0s, load SD checkpoint: 21.1s, create ui: 1.5s, gradio launch: 2.6s).
Loading model: t2iadapter_color_sd14v1 [8522029d]
Loaded state_dict from [/content/gdrive/.shortcut-targets-by-id/1-N00rILD1DFYx_xpfZmRc-FhO22x7pXE/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_color_sd14v1.pth]
ControlNet model t2iadapter_color_sd14v1 [8522029d] loaded.
Error running process: /content/gdrive/.shortcut-targets-by-id/1-N00rILD1DFYx_xpfZmRc-FhO22x7pXE/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/.shortcut-targets-by-id/1-N00rILD1DFYx_xpfZmRc-FhO22x7pXE/sd/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/content/gdrive/.shortcut-targets-by-id/1-N00rILD1DFYx_xpfZmRc-FhO22x7pXE/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 705, in process
    raise ValueError('controlnet is enabled but no input image is given')
ValueError: controlnet is enabled but no input image is given

100% 20/20 [00:09<00:00,  2.02it/s]
```

### Additional information

i use [TheLastBen notebook](https://github.com/TheLastBen/fast-stable-diffusion)
colab t4

**Comment by ljleb** [comment] 2023-03-31 22:18
I can reproduce. I'm really not sure why it does that.

**Comment by Orbitalz-eth** [comment] 2023-04-03 23:55
this issue is very annoying. can't even use controlnet at this point

**Comment by Jonseed** [comment] 2023-04-24 20:52
I get this error when trying to use new hires fix with ControlNet v1.1, which shouldn't need an input image, since it should use the low res image it first generates as input to make the control image, right?

**Comment by Andie-Squirrel** [comment] 2023-05-13 02:13
The issue remains

**Comment by bugsebe** [comment] 2023-08-21 08:53
Dildo it's august. and 2023. using pixel sized pixtures then faking their bigger, is fucking stupid.

**Comment by bugsebe** [comment] 2023-08-21 08:54
Who ever closed this mentally retarded.

**Comment by Z-YuPeng** [comment] 2023-10-16 10:11
When I use img2img generation, the image input panel disappears. What cause this problem? text2image do not have this problem and restart the stablewebui not work.
![R6fDHMBI2R](https://github.com/Mikubill/sd-webui-controlnet/assets/49511209/8fb713ee-6e16-40b3-8e41-58d94ee171fa)

**Comment by huchenlei** [comment] 2023-10-16 14:35
> When I use img2img generation, the image input panel disappears. What cause this problem? text2image do not have this problem and restart the stablewebui not work. ![R6fDHMBI2R](https://user-images.githubusercontent.com/49511209/275469465-8fb713ee-6e16-40b3-8e41-58d94ee171fa.jpg)

By default img2img controlnet uses img2img input from A1111 as input. If you want a different input image you need to check `Upload independent control image`.

**Comment by Z-YuPeng** [comment] 2023-10-16 14:39
> > When I use img2img generation, the image input panel disappears. What cause this problem? text2image do not have this problem and restart the stablewebui not work. ![R6fDHMBI2R](https://user-images.githubusercontent.com/49511209/275469465-8fb713ee-6e16-40b3-8e41-58d94ee171fa.jpg)
> 
> By default img2img controlnet uses img2img input from A1111 as input. If you want a different input image you need to check `Upload independent control image`.

Sloved, thanks a lot!

**Closed** 2023-11-21 20:18 UTC
Labels: help wanted
