### ISSUE TITLE
[Bug]: Crop and Resize using wrong ratio

### ISSUE THREAD

**Issue by Sakura-Luna** [Mikubill/sd-webui-controlnet#1170] opened 2023-05-06 06:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I use Crop and Resize and midas depth and pass in an image with the same resolution as the output, I find that the preprocessed result is inconsistent with the input image, it is obviously cropped after being stretched up and down. You can clearly see the position of the lights move up on the example.
![image](https://user-images.githubusercontent.com/53183413/236607904-3de4bf03-1fce-4654-946e-d373bdd77a4c.png)

### Steps to reproduce the problem

1. Set the output resolution
2. Set midas depth preprocessing
3. Pass in an image of the same size
4. Execution

### What should have happened?

The preprocessing results are consistent with the original image.

### Commit where the problem happens

webui: gradio 3.16 ver
controlnet: 1.1.136

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No error
```

**Comment by lllyasviel** [comment] 2023-05-06 09:35
I cannot see problem?

**Comment by Sakura-Luna** [comment] 2023-05-06 10:38
> I cannot see problem?

The preprocessing result is obviously stretched, there is a problem with the logic of Crop and Resize.
![image](https://user-images.githubusercontent.com/53183413/236619196-aba95205-efa8-4682-90d5-1f386eb07b42.png)

**Comment by lllyasviel** [comment] 2023-05-06 11:26
what is the size of image

**Comment by lllyasviel** [comment] 2023-05-06 11:28
ah this is a problem of stable diffusion. you can avoid this offset by using image sizes that can be divided by 64, like 512, 768, and so on

**Comment by Sakura-Luna** [comment] 2023-05-06 11:32
@lllyasviel You have no reason to close this question, the resolution is 512x768, exact multiple of 64.

**Comment by Sakura-Luna** [comment] 2023-05-06 11:36
The default length of WebUI is **a multiple of 8**, and the extension should be **fully compatible** with it.

Not only that, there **shouldn't be any stretching of the same input and output dimensions**.

**Comment by lllyasviel** [comment] 2023-05-06 11:37
but ur img is 720×960, as 512×682

**Comment by lllyasviel** [comment] 2023-05-06 11:37
![image](https://user-images.githubusercontent.com/19834515/236621732-3322c6a7-d583-4b48-b6e0-d895932e9a7b.png)

**Comment by Sakura-Luna** [comment] 2023-05-06 11:39
The image in the problem description is the original image, and this is the resolution.

![image](https://user-images.githubusercontent.com/53183413/236621780-54bb4087-0e80-483f-9756-263982703896.png)

**Comment by lllyasviel** [comment] 2023-05-06 11:41
> @lllyasviel You have **no reason** to close this question, the resolution is **512x768**, **exact multiple of 64**.

so your resolution is not 512x768, right?

what is your image size?

**Comment by Sakura-Luna** [comment] 2023-05-06 11:43
I misunderstood the resolution, the input and output are both 720x960, which is a multiple of 8 in standard.

**Comment by lllyasviel** [comment] 2023-05-06 11:48
i cannot see problem
![image](https://user-images.githubusercontent.com/19834515/236622135-9279a722-74bc-4cbf-a0db-f4ad8967739d.png)

your input image must have different size

**Comment by Sakura-Luna** [comment] 2023-05-06 11:51
Just Resize gives more accurate results (no stretching up and down), so I'm sure there is a logic problem with Crop and Resize.
I deleted the previous image because it seemed to be posted by mistake.
![image](https://user-images.githubusercontent.com/53183413/236622299-acfe528b-b173-470a-991f-2edb9128d83c.png)

**Comment by lllyasviel** [comment] 2023-05-06 11:57
"Just Resize" and "Crop and Resize" are different resizing methods and will give different results.

**Comment by Sakura-Luna** [comment] 2023-05-06 12:12
Here's another 720x960 example, the problem persists.

![image](https://user-images.githubusercontent.com/53183413/236623274-a1bce5b1-bf54-423d-ab1e-b9094fd1143f.png)

**Comment by Sakura-Luna** [comment] 2023-05-06 12:20
There is no problem on 512x768, but like I said above, the extension should be compatible with at least multiples of 8 resolutions to maintain consistency with the WebUI. And ideally the same input and output dimensions should not be stretched.

**Comment by lllyasviel** [comment] 2023-05-06 12:24
more information needed - please provide steps to reproduce problem

**Comment by Sakura-Luna** [comment] 2023-05-06 12:36
1. Generate an image with a size that is a multiple of 8, such as 720x960, without using hires fix.
2. Enable the extension, pass in the result, turn on midas depth preprocessing, depth 1.1 model.
3. Use Crop and Resize and Just Resize to generate images respectively. Comparing the results of the two, it can be found that the results of the former are stretched.

By the way, my test environment is this [fork](https://github.com/Sakura-Luna/stable-diffusion-webui), but it has no big difference from the WebUI under the original Gradio 3.16. If you can't reproduce on your environment, I would test the latest WebUI.

**Comment by lllyasviel** [comment] 2023-05-06 13:03
this problem cannot be solved because some other preprocessors like the mlsd requires image sizes to be devided by 64 and at the same time its outputs cannot be rezied because the edge needs to be one-pixel width

**Comment by Sakura-Luna** [comment] 2023-05-06 13:15
> this problem cannot be solved because some other preprocessors like the mlsd requires image sizes to be divided by 64 and at the same time its outputs cannot be rezied because the edge needs to be one-pixel width

I don't think it matters, it's very common practice to pass in a padded image and then crop the output, it's not a technical difficulty.

> it seems that the only solution is to use Just Resize when we know the resolution is same

At least a default handling should be added, using Just Resize directly when the dimensions are the same.

**Comment by lllyasviel** [comment] 2023-05-06 13:29
well let me take a look next time

**Comment by lllyasviel** [comment] 2023-05-06 18:02
fixed in 1.1.143

**Closed by lllyasviel** 2023-05-06 18:02 UTC
