### ISSUE TITLE
Blue screen when running dw_openpose_full

### ISSUE THREAD

**Issue by batblz** [Mikubill/sd-webui-controlnet#2184] opened 2023-10-19 23:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I'm having blue screen problems when running "dw_openpose_full", I've reinstalled A1111 and formatted my PC, nothing has solved it, when running "openpose_full" it works without problems. What could it be? I have an RTX 2070.

### Steps to reproduce the problem

1. ControlNet v1.1.411
2. Enable (Low VRAM, Pixel Perfect)
3. Control Type (OpenPose)
4. Preprocessor (dw_openpose_full)
5. Model (control_v11p_sd15_openpose [cab727d4])
6. Run preprocessor
7. CRASH!

### What should have happened?

Working without a blue screen.

### Commit where the problem happens

webui: A1111 (v1.6.0)
controlnet: v1.1.411

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No.
```

### List of enabled extensions

![er](https://github.com/Mikubill/sd-webui-controlnet/assets/51455767/7e4e5dd8-31a4-4aff-8abf-c922246b8783)

### Console logs

```Shell
I can't do that.
```

**Comment by HaomingXR** [comment] 2023-10-20 08:24
Looks like you don't have the Extension?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/125845771/37245732-ba5b-4146-8ab8-c37c8612a502)

**Comment by huchenlei** [comment] 2023-10-20 15:02
You don't need the DWPose repo checkout to use DWPose in ControlNet. That is not the cause for bluescreen.

**Comment by huchenlei** [comment] 2023-12-28 21:44
Closing as no other users have report the same issue.

**Closed by huchenlei** 2023-12-28 21:44 UTC
Labels: bug, help wanted, Not reproducable

**Comment by tacoturtle** [comment] 2024-07-28 03:15
Its happening to me now
