### ISSUE TITLE
[Bug]: Unable to use ip-adapter_face_id_plus

### ISSUE THREAD

**Issue by ducta11497** [Mikubill/sd-webui-controlnet#2582] opened 2024-01-25 09:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/9551207/2f718595-5a1b-419e-b342-7908677ad135)
When I try to make a preview use preprocessor **ip-adapter_face_id_plus** it show error above

### Steps to reproduce the problem

1. Open ControlNet v1.1.438
2. Pick a face image
3. Choose **Preprocessor** which is **ip-adapter_face_id_plus**
4. Click generate preview or start to generate a image
5. Got error when preview or not apply ControlNet to generated image

### What should have happened?

It should send some output to preview or change face to generated image

### Commit where the problem happens

webui: [v1.7.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cf2772fab0af5573da775e7437e6acdca424f26e)
controlnet: [6a1d882e](https://github.com/Mikubill/sd-webui-controlnet/commit/6a1d882e891c4b2e7986b9fda825fdbf24f7867e)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--allow-code --medvram --xformers --enable-insecure-extension-access --api
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/9551207/559fd205-86d1-46ee-9246-626d5f6c5335)

### Console logs

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/9551207/2f718595-5a1b-419e-b342-7908677ad135)

**Comment by Shangooriginal** [comment] 2024-01-25 11:58
Yep, since updating to the latest version, I am experiencing the same problem, non of the IP Adapters are working now, just generating errors. Everything worked fine yesterday.

**Comment by huchenlei** [comment] 2024-01-25 13:55
I am not sure if reverting #2583 helps as that was the only relevant PR landed yesterday. I cannot reproduce this issue locally though.

**Comment by ducta11497** [comment] 2024-01-26 01:27
Finally, I got it working. All you have to do is `pip install insightface==0.7.3` not `pip install insightface`. I don't know why but it's working now.

**Closed** 2024-01-26 01:43 UTC
Labels: bug, Not reproducable
