### ISSUE TITLE
Images in controlnet disappear when controlnet tab is closed and reopened again

### ISSUE THREAD

**Issue by sashasubbbb** [Mikubill/sd-webui-controlnet#882] opened 2023-04-18 07:08 UTC
Images in controlnet disappear when controlnet tab is closed and reopened again 
And when trying to generate this error appears:

> Traceback (most recent call last):█████████████████████████████████████████████████████| 25/25 [00:16<00:00,  1.63it/s]
>   File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
>     output = await app.get_blocks().process_api(
>   File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
>     inputs = self.preprocess_data(fn_index, inputs, state)
>   File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
>     processed_input.append(block.preprocess(inputs[i]))
>   File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 366, in svgPreprocess
>     if (inputs['image'].startswith("data:image/svg+xml;base64,") and svgsupport):
> AttributeError: 'dict' object has no attribute 'startswith'
> Traceback (most recent call last):
>   File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
>     output = await app.get_blocks().process_api(
>   File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
>     inputs = self.preprocess_data(fn_index, inputs, state)
>   File "B:\AIimages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
>     processed_input.append(block.preprocess(inputs[i]))
>   File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 366, in svgPreprocess
>     if (inputs['image'].startswith("data:image/svg+xml;base64,") and svgsupport):
> AttributeError: 'dict' object has no attribute 'startswith'

**Comment by ljleb** [comment] 2023-04-18 07:12
duplicate of #677

**Closed** 2023-04-18 07:16 UTC
