### ISSUE TITLE
[Unittest] WebUI print out error and stacktrace in terminal but still return HTTP 200

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#1135] opened 2023-05-03 01:21 UTC
After adding unittests to include preprocessors in the web_api tests, I introduced an error intentionally, but the test still passes. 

I get following stacktrace in the commandline:
```
Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1223, in process
    detected_map, is_image = preprocessor(input_image, res=preprocessor_resolution, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
TypeError: OpenposeModel.run_model() missing 1 required positional argument: 'json_pose_callback'
```

Since we are invoking the path defined in WebUI, I suspect the error handling code there might have some problem.

**Comment by huchenlei** [comment] 2023-05-03 01:55
Obviously no further action is done [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/5ab7f213bec2f816f9c5644becb32eb72c8ffb89/modules/scripts.py#L413):
```python
def process(self, p):
        for script in self.alwayson_scripts:
            try:
                script_args = p.script_args[script.args_from:script.args_to]
                script.process(p, *script_args)
            except Exception:
                print(f"Error running process: {script.filename}", file=sys.stderr)
                print(traceback.format_exc(), file=sys.stderr)
                # That's it? Should't we return something to the user?
```

**Comment by lllyasviel** [comment] 2023-05-04 18:28
well idk what to do

**Comment by huchenlei** [comment] 2023-05-04 19:20
We probably need to submit a PR to WebUI to fix this. Otherwise there is no way in the test we are going to detect the failures.

**Comment by lllyasviel** [comment] 2023-05-04 19:22
or we can hack that func just like webui hack sd's ldm - it just make spaghetti more spaghetti

**Comment by ljleb** [comment] 2023-05-05 17:58
#678 fixes this. Duplicate of #615

**Closed** 2023-05-05 23:55 UTC
