### ISSUE TITLE
openpose Preview and Model stopped working after update to 1.1

### ISSUE THREAD

**Issue by EricTsutola** [Mikubill/sd-webui-controlnet#901] opened 2023-04-18 19:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Running an Radeon 7900 XTX on windows 10. 

After updating to 1.1, lots of stuff such as normal maps, and depth maps worked as before they didn't, however I lost the ability to use any openpose option, I have tried uninstalling the extension, deleting all related folders but the same error occurs each time.

I've seen 2 people bring this up also with 6900xt's so hopefully it isn't just me.

### Steps to reproduce the problem

Install
Open Control net
Select picture
Select any openpose preprocessor 
Click Preview
Error Occurs

### What should have happened?

openpose used to work before update, although getting things to work on the 7900 xtx has sure been something so im not surprised it doesn't work anymore.

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/fd59537df9420bb14c1d6330ec59e30ce870a481
controlnet: 7d28d00e
python: 3.10.6  
torch: 1.13.1+cpu   
xformers: N/A 

### Command Line Arguments

```Shell
--opt-sub-quad-attention --disable-nan-check --autolaunch --no-half --opt-split-attention --medvram
```

### Console logs

```Shell
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 398, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "F:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\processor.py", line 196, in openpose
    result = model_openpose(img)
  File "F:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 84, in __call__
    candidate, subset = self.body_estimation(oriImg)
  File "F:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\body.py", line 48, in __call__
    Mconv7_stage6_L1, Mconv7_stage6_L2 = self.model(data)
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\model.py", line 116, in forward
    out1 = self.model0(x)
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 319, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (PrivateUse1FloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

### Additional information

I am quite new to github and all of this so I apologize in advanced.

**Comment by jyomu** [comment] 2023-04-18 21:07
The likely cause of the issue is a regression related to commit b7a205841950a6cd90d944caae0e40c4c30e5cc6. This change caused tensors to not be properly moved to the appropriate device, leading to data type mismatches.

before:
```
data = data.to(devices.get_device_for("controlnet"))
```
after:
```
if torch.cuda.is_available():
    data = data.cuda()
```
The issue was resolved by reverting to the original method. This ensured that the data was properly moved to the GPU and prevented data type mismatches from occurring at runtime.

**Comment by lllyasviel** [comment] 2023-04-18 21:30
how to reproduce the problem? do i need an amd card to reproduce it?

**Comment by lllyasviel** [comment] 2023-04-18 21:38
or do i reproduce it with cpu?

**Comment by jyomu** [comment] 2023-04-18 21:39
Using stable-diffusion-webui-directml can reproduce the issue. 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs

Since DirectML was supposed to run based on DirectX, it may work even without an AMDGPU.

PrivateUse1 is DirectML device name.

**Comment by lllyasviel** [comment] 2023-04-18 21:41
is that just change one line of code? will fix soon. not sure will it work

**Comment by lllyasviel** [comment] 2023-04-18 21:43
does other models like softedge_hed and depth work?

**Comment by EricTsutola** [comment] 2023-04-18 21:44
They do work for me yes. depth was actually fixed after updating, was broken before.

**Comment by EricTsutola** [comment] 2023-04-18 21:51
Its a gamble on which preprocessors do work and I can provide any errors they give or just say which ones, I was just worried for openpose since I use it most.

**Comment by jyomu** [comment] 2023-04-18 21:54
Based on [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/b48ae2ba41a293bee9aaa22afe7a2b7e39a39fe0/modules/devices.py#L65-L71), any code that includes torch.cuda.is_available() should use module.devices instead.
and [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/b48ae2ba41a293bee9aaa22afe7a2b7e39a39fe0/modules/devices.py#L48-L58)

**Comment by lllyasviel** [comment] 2023-04-18 21:56
ok i know. will fix in 24 hours

**Comment by lllyasviel** [comment] 2023-04-19 07:46
fixed

**Closed by lllyasviel** 2023-04-19 07:46 UTC
