### ISSUE TITLE
[Bug]: Image used for controlnet disappears upon using txt2img or even closing the controlnet window

### ISSUE THREAD

**Issue by Orbitalz-eth** [Mikubill/sd-webui-controlnet#682] opened 2023-03-30 15:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I added my image that I wanted to use with controlnet's "canny" option. I set up all the settings, then when I collapse the controlnet window, the image I'm using disappears. and when I click on the "image add" window, nothing happens, there's no popup. The same thing happens when I run the txt2img, the canny image disappears.

### Steps to reproduce the problem

1. Add an image to controlnet. 
2. use canny and along cannyFP16 or whatever its called.
3. collapse the controlnet window and reopen it. or use txt2img

### What should have happened?

the controlnet img shouldve stayed and I should also be able to click on it and change the image.

### Commit where the problem happens

webui: auto1111 commit: [22bcc7be]
controlnet:  241c05f8 (Thu Mar 23 15:18:35 2023)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
no logs
```

**Comment by ljleb** [comment] 2023-03-30 22:09
Duplicate of #677

**Closed** 2023-04-18 07:19 UTC
