### ISSUE TITLE
[bug?] Warning: StyleAdapter and cfg/guess mode may not works due to non-batch-cond inference

### ISSUE THREAD

**Issue by zark119** [Mikubill/sd-webui-controlnet#566] opened 2023-03-12 07:32 UTC
This warning appears when the negative prompt is above 75 characters, then the style adapter has no effect. I am not sure, if this is intended feature or a bug...

**Comment by SergeySypalo** [comment] 2023-03-15 13:34
Duplicate of https://github.com/Mikubill/sd-webui-controlnet/discussions/521

**Closed** 2023-05-05 19:15 UTC
