### ISSUE TITLE
combine control net with ultimate sd upscale

### ISSUE THREAD

**Issue by Nazzaroth2** [Mikubill/sd-webui-controlnet#43] opened 2023-02-14 19:03 UTC
would it be possible to combine controlnet with this extention?
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111 (or would that developer have to integrate the functionality?)

currently it copies the feature-image for every tile that is used in the upscale and thus copies the image over itself. The improved detail coherency from canary or hde might work wonders to allow regaining detailes (especially thinking about hands etc.)

EDIT:
just found the thread talking about general upscaling the mask images. I do think the combination with ultimate upscale would be preferable to general upscaling though, because the individual tile-sizes stay in 512-768px range and thus should work better with the trained models from controlnet, hopefully XP

**Comment by Danamir** [comment] 2023-02-15 01:53
I concur. 

With segmentation preprocessor, it could identify each segment and avoid rendering faces and hands anywhere. It would really boost the SD upscalers usability !

**Comment by Preston-L** [comment] 2023-02-23 19:56
With this fantastic combo, one can do incredible style transformations while preserving intricate details!

**Comment by Lute-4** [comment] 2023-02-24 22:03
+1 :)

https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/issues/36

**Comment by Danamir** [comment] 2023-03-09 01:52
There must have been some improvements, we can now use controlnet and ultimate sd upscale at the same time, but still with some limitations.

I found the best results by using canny preprocessor, with the annotator resolution set to the sd upscale tile size + padding. There is still a bug, the mask blur is not taken into account so you have to set it to zero and have seams, or have your final image squished.

Here is an example, let's take this 1024x1024 image and upscale it to 1536x1536 by using four 768 tiles. I will be using a 128 padding in SD upscale.

The original image : 
![07102-303429207-photography_,half body portrait, elf woman, cute face, golden braided hair, diaphanous magic armor, fantasy street, detailed env (DPM++ SDE Karras, 16, 6)](https://user-images.githubusercontent.com/15424198/223891928-94b0cd8f-dd9e-462d-8b99-b5f0c1815e29.png)

An upscale without controlnet, and a denoising set  to 0.8 on purpose to illustrate the problem :  
![07154-303429207 0-photography_,half body portrait, elf woman, cute face, golden braided hair, diaphanous magic armor, fantasy street, detailed env (DPM++ 2M Karras, 16, 6)](https://user-images.githubusercontent.com/15424198/223892217-790d6686-687f-4589-939c-1d653fc2168a.png)

Now on to ControlNet, preprocessor = canny, model = control_canny, annotator resolution 768+128 = 896 .

Without mask blur, there are some very nice details due to the 0.8 denoising, the face structure is respected with the help of canny, but there are very visible seams due to the lack of mask blur :  
![07152-303429207 0-photography_,half body portrait, elf woman, cute face, golden braided hair, diaphanous magic armor, fantasy street, detailed env (DPM++ 2M Karras, 16, 6)](https://user-images.githubusercontent.com/15424198/223892520-a69a0455-8998-4fa7-b4ce-e3e10a7972f4.png)

And finally to illustrate the current remaining bug with mask blur, the facial features are squished because canny is applied on a quarter of the image + mask blur size, but the seams are almost gone :  

![07153-303429207 0-photography_,half body portrait, elf woman, cute face, golden braided hair, diaphanous magic armor, fantasy street, detailed env (DPM++ 2M Karras, 16, 6)](https://user-images.githubusercontent.com/15424198/223892873-1007f9c8-e110-4907-a841-16e8a7ea44be.png)

NB: The denoising setting set to 0.8 was obviously set too high only to illustrate the problem. In this particular upscaling case controlnet is not really necessary because a lower denoise is enough. But there are many cases when a little bit of guidance can go a long way if you want to keep the denoising between 0.4 and 0.5 to have nice details, and still keep image coherency at higher tiles resolution. 

Here is the result by using "normally" SD upscale, 128 padding, mask blur 8, denoising 0.4. :  
![07157-303429207 0-photography_,half body portrait, elf woman, cute face, golden braided hair, diaphanous magic armor, fantasy street, detailed env (DPM++ 2M Karras, 16, 6)](https://user-images.githubusercontent.com/15424198/223894112-9dfebada-51a9-4b57-9f11-de7b97802bb8.png)

**Comment by taylorhand** [comment] 2023-03-13 21:55
@Danamir Thanks for sharing your settings and results, I was also digging into this and seeing if ultimate sd upscale needed to be patched or if the fix can be done in ControlNet. 

After some testing this weekend, I have a possible fix for this and it would also address another issue (https://github.com/Mikubill/sd-webui-controlnet/discussions/391). Still working on figuring out the mask blur issue.

The main issue is a missing resize and crop during the inpainting check ([Line 770](https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/controlnet.py#L770)). This logic is applied in img2img (see `detectmap_proc()` for resizing logic), but not when performing any inpainting, which ultimate sd upscale uses. 

Currently it only works if the final output image is the same size as the ControlNet image, otherwise it gets forced to map 1-to-1 from the top-left corner. This can be confirmed by using any two images (one for img2img, other for ControlNet) where the image sizes do not match.

Current code:
```python
if issubclass(type(p), StableDiffusionProcessingImg2Img) and p.inpaint_full_res == True and p.image_mask is not None:
    input_image = Image.fromarray(input_image)
    mask = p.image_mask.convert('L')
    crop_region = masking.get_crop_region(np.array(mask), p.inpaint_full_res_padding)
    crop_region = masking.expand_crop_region(crop_region, p.width, p.height, mask.width, mask.height)

    input_image = input_image.crop(crop_region)
    input_image = images.resize_image(2, input_image, p.width, p.height)
    input_image = HWC3(np.asarray(input_image))
```
`input_image` is cropped based on the mask and cropping region provided, but doesn't consider any scaling prior.

![controlnet_old_behavior](https://user-images.githubusercontent.com/82241809/224840829-b2851caa-2397-405c-a0e1-136537638bf1.png)

---

Possible solution:
```python
if issubclass(type(p), StableDiffusionProcessingImg2Img) and p.inpaint_full_res == True and p.image_mask is not None:
    input_image = Image.fromarray(input_image)
    mask = p.image_mask.convert('L')
    crop_region = masking.get_crop_region(np.array(mask), p.inpaint_full_res_padding)
    crop_region = masking.expand_crop_region(crop_region, p.width, p.height, mask.width, mask.height)
    
    # Check resizing mode, scaling ControlNet image to upscaled resolution before cropping to tile region.
    if resize_mode == "Scale to Fit (Inner Fit)":
        input_image = images.resize_image(2, input_image, mask.width, mask.height)
    elif resize_mode == "Envelope (Outer Fit)":
        input_image = images.resize_image(1, input_image, mask.width, mask.height)
    else:
        input_image = images.resize_image(0, input_image, mask.width, mask.height)

    input_image = input_image.crop(crop_region)
    input_image = images.resize_image(2, input_image, p.width, p.height)
    input_image = HWC3(np.asarray(input_image))
```

Scale before cropping (inner fit):
![controlnet_new_behavior_innerfit](https://user-images.githubusercontent.com/82241809/224840823-38208721-1b8c-48ed-a51e-8359060a917a.png)

**Comment by Lute-4** [comment] 2023-04-18 11:19
Any news guys? :)

**Comment by ntrouve-onera** [comment] 2023-04-19 16:14
I did test with a premade controlnet image (generated outside the webui with blender) and it works just fine. 

As a workaround until it gets fixed you could find a way to run the preprocessor alone on the whole upscaled image then input it manually into the webui.

**Closed** 2023-05-05 19:12 UTC

**Comment by feffy380** [comment] 2023-07-30 14:36
This should not have been closed. The mask blur issue is still present as of July 30

Original image:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/114889020/88b5d460-40b6-4568-bd10-77531015cc07)

Upscaled with Ultimate SD Upscale extension:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/114889020/ef618fac-1bd2-41d6-a0b4-97d1ab629b88)

Settings:
black lines on white background
Steps: 5, Sampler: DPM++ 2M SDE Karras, CFG scale: 7, Seed: 3681399156, Size: 1024x1024, Model hash: cc6cb27103, Model: sd-v1-5-pruned-emaonly, Denoising strength: 1, Ultimate SD upscale upscaler: Lanczos, Ultimate SD upscale tile_width: 512, Ultimate SD upscale tile_height: 512, Ultimate SD upscale mask_blur: 8, Ultimate SD upscale padding: 32, DDIM Trailing: True, CFG Rescale: 0.7, ControlNet 0: "preprocessor: none, model: control_v11f1e_sd15_tile [a371b31b], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: False, control mode: Balanced, preprocessor params: (512, 1, 64)", Schedule type: exponential, Version: v1.5.1

As mentioned above, setting mask blur to zero avoids the tile size discrepancy but results in visible seams:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/114889020/d5c7a5bc-2acd-4035-ad87-5a7b1f4b24f5)
