### ISSUE TITLE
[Bug]: TypeError: unhashable type: 'slice' hook.py

### ISSUE THREAD

**Issue by BrentWilkins** [Mikubill/sd-webui-controlnet#1834] opened 2023-07-26 15:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I was trying to follow [this tutorial](https://stable-diffusion-art.com/controlnet/). On generation, I get ~~this error~~ (moved lower in console output section):

Rather than passing a `list` as `prompt_context_is_marked` is clearly written to accept, [this block](https://github.com/Mikubill/sd-webui-controlnet/blob/ff7aad9a7045a4224da447c87bd37a189db01b94/scripts/hook.py#L47) is passing the `cond` `dict`. [This line](https://github.com/Mikubill/sd-webui-controlnet/blob/ff7aad9a7045a4224da447c87bd37a189db01b94/scripts/hook.py#L29) cannot do high dimension NumPy list slicing on a `dict`.

### Steps to reproduce the problem

See instructions [here](https://stable-diffusion-art.com/controlnet/).

### What should have happened?

I should have gotten some images.

### Commit where the problem happens

webui: a3ddf464a2ed24c999f67ddfef7969f8291567be
controlnet: ff7aad9a7045a4224da447c87bd37a189db01b94

### What browsers do you use to access the UI ?

Mozilla Firefox, Brave

### Command Line Arguments

```Shell
I'm running CPU only:

export COMMANDLINE_ARGS="--no-half-vae --lowvram --skip-torch-cuda-test --no-half --listen"
```

### List of enabled extensions

| Extension |	URL |	Branch |	Version |	Date |	Update |
| ---------- | ------ | ----------- | -------- | ------ | ---------- |
| sd-webui-controlnet 	| https://github.com/Mikubill/sd-webui-controlnet |	main |	ff7aad9a 	| Wed Jul 26 12:43:53 2023 	| unknown |
| LDSR |	built-in |	None 	|	| Wed Jul 26 14:28:05 2023 	|
| Lora 	| built-in |	None 	| |	Wed Jul 26 14:28:05 2023 	|
| ScuNET |	built-in |	None 	|	| Wed Jul 26 14:28:05 2023 	|
| SwinIR |	built-in |	None 	|	| Wed Jul 26 14:28:05 2023 	|
| canvas-zoom-and-pan |	built-in |	None 	|	| Wed Jul 26 14:28:05 2023 	|
| extra-options-section |	built-in |	None 	|	| Wed Jul 26 14:28:05 2023 	|
| mobile |	built-in |	None 	|	| Wed Jul 26 14:28:05 2023 	|
| prompt-bracket-checker 	| built-in |	None 	|	| Wed Jul 26 14:28:05 2023 	|

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on brent user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Jul 22 2023, 17:45:09) [GCC 11.3.0]
Version: v1.5.0
Commit hash: a3ddf464a2ed24c999f67ddfef7969f8291567be

Launching Web UI with arguments: --no-half-vae --lowvram --skip-torch-cuda-test --no-half --listen
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+rocm5.4.2)
    Python  3.10.11 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
No module 'xformers'. Proceeding without it.
Warning: caught exception 'No HIP GPUs are available', memory monitor disabled
2023-07-26 09:21:37,797 - ControlNet - INFO - ControlNet v1.1.233
ControlNet preprocessor location: /.../stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-07-26 09:21:37,838 - ControlNet - INFO - ControlNet v1.1.233
Loading weights [1f69731261] from /.../stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_0.9.safetensors
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 3.2s (launcher: 0.2s, import torch: 1.2s, import gradio: 0.4s, setup paths: 0.3s, other imports: 0.2s, load scripts: 0.4s, create ui: 0.3s).
Creating model from config: /.../stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml
Applying attention optimization: InvokeAI... done.
Model loaded in 2.2s (load weights from disk: 0.6s, create model: 0.4s, apply weights to model: 0.9s, calculate empty prompt: 0.3s).
2023-07-26 09:00:55,211 - ControlNet - INFO - Loading model: control_v11p_sd15_openpose [cab727d4]
2023-07-26 09:00:55,506 - ControlNet - INFO - Loaded state_dict from [/.../stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.pth]
2023-07-26 09:00:55,506 - ControlNet - INFO - Loading config: /.../stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.yaml
2023-07-26 09:00:56,678 - ControlNet - INFO - ControlNet model control_v11p_sd15_openpose [cab727d4] loaded.
2023-07-26 09:00:56,679 - ControlNet - INFO - Loading preprocessor: openpose
2023-07-26 09:00:56,679 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: /.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/.../stable-diffusion-webui/modules/scripts.py", line 495, in process
        script.process(p, *script_args)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 930, in process
        self.latest_network.hook(model=unet, sd_ldm=sd_ldm, control_params=forward_params, process=p)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 757, in hook
        module = model.input_blocks[i]
      File "/.../stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 295, in __getitem__
        return self._modules[self._get_abs_string_index(idx)]
      File "/.../stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 285, in _get_abs_string_index
        raise IndexError('index {} is out of range'.format(idx))
    IndexError: index 10 is out of range

---
*** Error completing request
*** Arguments: ('task(kfjisepq9qjr0pd)', 0, 'full-body, a young female, highlights in hair, dancing outside a restaurant, brown eyes, wearing jeans', 'disfigured, ugly, bad, immature', [], <PIL.Image.Image image mode=RGBA size=640x960 at 0x7FC05095B7F0>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x7fc05095b340>, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fc05915e680>, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, 50) {}
    Traceback (most recent call last):
      File "/.../stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/.../stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/.../stable-diffusion-webui/modules/img2img.py", line 232, in img2img
        processed = process_images(p)
      File "/.../stable-diffusion-webui/modules/processing.py", line 673, in process_images
        res = process_images_inner(p)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/.../stable-diffusion-webui/modules/processing.py", line 793, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 346, in process_sample
        mark_prompt_context(kwargs.get('conditioning', []), positive=True)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 41, in mark_prompt_context
        x.batch = mark_prompt_context(x.batch, positive)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 38, in mark_prompt_context
        x[i] = mark_prompt_context(x[i], positive)
      File "/./stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 38, in mark_prompt_context
        x[i] = mark_prompt_context(x[i], positive)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 44, in mark_prompt_context
        x.schedules = mark_prompt_context(x.schedules, positive)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 38, in mark_prompt_context
        x[i] = mark_prompt_context(x[i], positive)
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 48, in mark_prompt_context
        if prompt_context_is_marked(cond):
      File "/.../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 29, in prompt_context_is_marked
        t = x[..., 0, :]
    TypeError: unhashable type: 'slice'

---
```

**Comment by huchenlei** [comment] 2023-07-26 16:03
Assigning to author of https://github.com/Mikubill/sd-webui-controlnet/blob/ff7aad9a7045a4224da447c87bd37a189db01b94/scripts/hook.py#L47

**Comment by huchenlei** [comment] 2023-07-26 16:43
SDXL is probably the cause, we should find a way to detect it and provide more meaningful error message.

**Comment by Kadah** [comment] 2023-07-27 11:14
It is SDXL. There's a few extensions that are getting this, likely any that hooks or hijacks into gen.

**Comment by helloansuman** [comment] 2023-07-28 10:03
So we cannot use controlnet if we are using SDXL

**Closed** 2023-07-28 14:26 UTC

**Comment by garychan22** [comment] 2023-08-15 07:21
I have implemented reference only into sd-xl but I found that the effect of referencing is weak. has anyone known the reason?
